language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install ."
before_script:
  - "pip install git+https://github.com/Rostlab/nalaf.git"
  - "python -m nalaf.download_corpora"
  - pip install codecov
  - pip install gensim
after_success:
  - codecov
script:
  - "nosetests -a \"!slow\""
#  - "python nala.py -p 2581245"
branches:
  only:
    - master
    - develop
